// Billing module — placeholder
// Entity: billing_charges (ARCHITECTURE.md §6.1)
// Charges generated by AUHMS and exported to Colleague ERP.
// AUHMS never processes payments — billing stays in Colleague.
// exported_at and export_batch_id track export status for reconciliation.
//
// Integration notes (ARCHITECTURE.md §7.1):
//   - Colleague is the system of record for billing
//   - AUHMS produces an exportable charge file in the format Colleague expects
//   - Export format (charge codes, file format) TBD — requires coordination
//     with Finance and IT before implementation
//   - Nightly batch sync assumed — do not design for real-time Colleague availability
//
// TODO: Implement charge list (filterable by term/export status), generate
// export batch, download export file in Colleague format, mark as exported.
// Requires: HOUSING_ADMIN role (sensitive financial data).

export const metadata = {
  title: "Billing — AUHMS",
};

export default function BillingPage() {
  return (
    <div>
      <h1>Billing Charges</h1>
      <p style={{ color: "#6b7280" }}>
        Charges generated for export to Colleague ERP. AUHMS does not process
        payments. Placeholder — implementation pending.
      </p>
      <p style={{ color: "#9ca3af", fontSize: "0.875rem" }}>
        Export format TBD — requires coordination with Finance and IT.
      </p>
    </div>
  );
}
